### ISSUE TITLE
Getting error while trying to run using command: npm run serve

### ISSUE THREAD

**Issue by manojadams** [jbrun0r/chatbot-front-end#1]
Getting error while trying to run with command: `npm run seve`
```
> chatbot@0.1.0 serve /exp/chatbot-front-end
> vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'upgrade' of undefined
TypeError: Cannot read property 'upgrade' of undefined
    at Server.<anonymous> (/Users/mbaruah/projects/ping/exp/chatbot-front-end/node_modules/webpack-dev-server/lib/Server.js:1937:26)
    at Array.forEach (<anonymous>)
    at Server.initialize (/Users/mbaruah/projects/ping/exp/chatbot-front-end/node_modules/webpack-dev-server/lib/Server.js:1932:29)
    at Server.start (/Users/mbaruah/projects/ping/exp/chatbot-front-end/node_modules/webpack-dev-server/lib/Server.js:3356:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chatbot@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chatbot@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbaruah/.npm/_logs/2024-10-30T09_17_20_861Z-debug.log
```

**Comment by dimabel** [comment]
To fix this, you have to add and environment file like the .env.example file.
Simply add .env.development and add the relevant variables.
